services:
  - type: web
    name: music-kino-bot
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMINS
        sync: false
      - key: KINO_CHANNEL_ID
        sync: false
      - key: SECRET_PIN
        value: "0009"
      - key: DB_PATH
        value: data/bot.db
